# Generated by Django 3.0.3 on 2020-04-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Handling',
            fields=[
                ('f1', models.IntegerField(blank=True, null=True)),
                ('hazclass_t_toxic_f_flam_r_reactive_c_corrosive', models.IntegerField(db_column='HazClass_T=Toxic_F=Flam_R=Reactive_C=Corrosive', primary_key=True, serialize=False)),
                ('inhalation', models.TextField(blank=True, db_column='Inhalation', null=True)),
                ('skin_contact', models.TextField(blank=True, db_column='Skin_contact', null=True)),
                ('eye_contact', models.TextField(blank=True, db_column='Eye_contact', null=True)),
                ('ingestion', models.TextField(blank=True, db_column='Ingestion', null=True)),
            ],
            options={
                'db_table': 'handling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hazardchemicals',
            fields=[
                ('chemical_name', models.CharField(db_column='Chemical_Name', max_length=255, primary_key=True, serialize=False)),
                ('hazardstatementcode', models.CharField(db_column='HazardStatementCode', max_length=255)),
                ('hazard_statement', models.CharField(blank=True, db_column='Hazard_Statement', max_length=255, null=True)),
                ('hazard_word', models.CharField(blank=True, db_column='Hazard_Word', max_length=255, null=True)),
                ('ghs_code', models.CharField(blank=True, db_column='GHS_Code', max_length=255, null=True)),
            ],
            options={
                'db_table': 'HazardChemicals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pictogramcode',
            fields=[
                ('hazardstatementcode', models.CharField(db_column='HazardStatementCode', max_length=255, primary_key=True, serialize=False)),
                ('prevention_code', models.CharField(blank=True, db_column='Prevention_Code', max_length=255, null=True)),
                ('response_code', models.CharField(blank=True, db_column='Response_Code', max_length=255, null=True)),
                ('storage_code', models.CharField(blank=True, db_column='Storage_Code', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PictogramCode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precautions',
            fields=[
                ('f1', models.CharField(blank=True, max_length=255, null=True)),
                ('hazclass_t_toxic_f_flam_r_reactive_c_corrosive', models.IntegerField(db_column='HazClass_T=Toxic_F=Flam_R=Reactive_C=Corrosive', primary_key=True, serialize=False)),
                ('precautions', models.TextField(blank=True, db_column='Precautions', null=True)),
            ],
            options={
                'db_table': 'precautions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precautionstm',
            fields=[
                ('pictogramcode', models.CharField(db_column='PictogramCode', max_length=255, primary_key=True, serialize=False)),
                ('statement', models.CharField(blank=True, db_column='Statement', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PrecautionStm',
                'managed': False,
            },
        ),
    ]
